### ISSUE TITLE
Cannot filter by grade

### ISSUE THREAD

**Issue by killakalle** [theCrag/tca#111]
**What happened?**

1. Open any crag that has routes
2. Go to Search within that crag
3. Change the slider to restrict the range
4. See if the route list updates - it does not
5. Click into the search field and try to search for an empty name to try to trigger the search with updated grade range - it does not work

It seems it's not possible to filter for a grade range unless you type something into the Search

Example url(s) to reproduce the problem:

Ideally also provide screenshots:
![image](https://user-images.githubusercontent.com/30682796/116202157-94200400-a73a-11eb-9510-56fc4a857a52.png)

**What you expected:**

* [ ] possibility to filter by grade range only

**Comment by bkucsera** [comment]
Fixed, please check.

**Comment by rouletout** [comment]
This works for me - please check @killakalle

**Comment by killakalle** [comment]
Works somewhat, but not consistently. See examples below:

From 6b+ to 6b+ --- OK
![image](https://user-images.githubusercontent.com/30682796/117065160-67b24c00-ad27-11eb-8ebe-037cf510b7b0.png)

From 6b+ to 6c --- NOK (no results)
![image](https://user-images.githubusercontent.com/30682796/117065283-98928100-ad27-11eb-8e9a-093583c8d3de.png)

From 6c to 6c --- NOK (no results)
![image](https://user-images.githubusercontent.com/30682796/117065860-4736c180-ad28-11eb-8cf9-ddfd0af52bdf.png)

From 6c to 6c+ --- OK
![image](https://user-images.githubusercontent.com/30682796/117065906-56b60a80-ad28-11eb-99da-7dd9e8699727.png)

From 7a to 7b --- OK
![image](https://user-images.githubusercontent.com/30682796/117066027-849b4f00-ad28-11eb-915a-f6d503cbbb55.png)


From 7a+ to 7c --- NOK (only one 7a+)
![image](https://user-images.githubusercontent.com/30682796/117065972-6f262500-ad28-11eb-94f1-34714932ed64.png)

From 7a+ to 7a+ --- NOK (only one 7a+)
![image](https://user-images.githubusercontent.com/30682796/117066111-9c72d300-ad28-11eb-89a5-80f700ac8cad.png)

**Comment by bkucsera** [comment]
Thanks for the ticket, fixed again, please check.  v 4.0.3 (3)

**Comment by killakalle** [comment]
@bkucsera 

I'm still getting the same results as in my screenshots above.
Am I on the right version?

![image](https://user-images.githubusercontent.com/30682796/125322640-49c42180-e33e-11eb-9e3e-d7bf1e959cd2.png)
![image](https://user-images.githubusercontent.com/30682796/125322666-4f216c00-e33e-11eb-8d21-02f09a885cdf.png)

**Comment by rouletout** [comment]
Fixed, closing
