### ISSUE TITLE
Tabs can't be swiped

### ISSUE THREAD

**Issue by matozoid** [theCrag/tca#36]
When looking at Wallis/Rawyl I'm trying to swipe from INFO to SECTORS, but it keeps flopping back to INFO.

Oh, going through the tabs seems to magically fix it. Maybe the tabs can't be swiped to because they are not "loaded" yet?

Oh no, it's broken again.

**Comment by bkucsera** [comment]
We had the same issue when swiping topos. 
We will fix this as well, thanks for the comment!

**Comment by bkucsera** [comment]
We have modified a bit. Now this can happen only on the Info tab, but not the others.
On the Info tab 2 different swiping can hit each other: vertical swiping for pull to refresh and horizontal swipe to switch between tabs. If you do a clear horizontal swipe, it will swipe to the next tab.

**Comment by rouletout** [comment]
@matozoid is this good now - we think it is fixed

**Comment by bkucsera** [comment]
Fixed (v151), please check and close if works properly.

**Comment by killakalle** [comment]
When I open the app fresh and open the first area, then I cannot swipe to
the next tab, e.g. from Info to Areas.
If I then click on Areas, then I can swipe back and forth. If I now
navigate to a sub-area, I can again not swipe right. Then, again, if I
click on Areas, thereafter I can swipe back and forth.

I'm on Android.

Edit:
Just reading your comment on vertical vs horizontal swiping.
It seems vertical swiping is disabled after you have gone to Areas once, then horizontal swiping works smoothly. Before it doesn't really work - you need to be too precise.

I would argue that content update of areas/nodes is not that frequent to justify such a difficult UI. It's probably okay to load the node once you open it. However, I don't think it needs to refreshed once you have already opened it.

**Comment by bkucsera** [comment]
This was a bug as well :) 
Swipe to refresh was disabled by pages, but no we disabled at all, on node screens. 

If you cannot swipe for the next tab after the very first start of the app, it can be because of the downloading and background-parsing of data. 
I tried this and i did not have this issue. 
Can you please check again? Maybe wait a few more second after entering the first node.

**Comment by killakalle** [comment]
Still the same for me. Do you need to publish a new version first? Or do I
need to update the app somehow?

**Comment by bkucsera** [comment]
Swipe to refresh will be disabled in v152. At the moment v151 is in the Play Store.
Or you mean "same", for any of the previous bugs mentioned in this topic?

**Comment by killakalle** [comment]
okay, will test with the next version.

Can I somehow see the current version number? The app info on Google play
says 3.0.63. Don't know how to connect this with the version numbers you
are using.

**Comment by rouletout** [comment]
@killakalle just go to your profile - from tehre you see the current version (eg 152)

**Comment by rouletout** [comment]
@killakalle please check in release 153 which is out now

**Comment by killakalle** [comment]
Looks good now!

**Comment by rouletout** [comment]
Closing
